### ISSUE TITLE
Encoding chunks do not match inferred chunks

### ISSUE THREAD

**Issue by caiostringari** [xpublish-community/xpublish#207]
Hi,

I am having problems with the`/zarr/get_zarr_metadata` endpoint. I can start the server and I see my dataset but when I try to read data from the client side, I get `ValueError: Encoding chunks do not match inferred chunks`.

I tried to explicitly change the chunks / encoding but it did not seem to work.

My code looks something like this:

```python
import zarr
import xarray as xr
from azure.storage.blob import ContainerClient

container_client = ContainerClient("some_url", container_name="some_name", credential="some_credentials")
store = zarr.ABSStore(client=container_client, prefix="file.zarr")

ds = xr.open_zarr(store, consolidated=True, overwrite_encoded_chunks=True)  # do I need overwrite_encoded_chunks?
ds = ds.chunk({"time": 2**12, "feature_id": 2**16})  # do I need this?
ds.encoding = {"time": 2**12, "feature_id": 2**16} # do I need this?
```

Any ideas?

Thank you very much

**Comment by xaviernogueira** [comment]
@abkfenris 
So I came to Issues to point out a similar problem. Here is more information.

# Bug description
* **Endpoint with this error: `/zarr/.zmetadata` and `/zarr/{var}/{chunk}`**.
* With the OSN data shown below `utils.zarr.jsonify_zmetadata()` fails with a key error (see "Error code w/ OSN data").
* With the requester pays S3 data either I get the same issue as the OSN data or `utils.zarr._extract_zarray()` fails with a ValueError as described by @caiostringari. not sure why I get different issues when I try at different times. **This to me suggests a cacheing issue?**
* In both cases when I intercept with a breakpoint, I can print out the same variable "ACDEWC"'s chunks as normal.
* `/zarr/.zgroup` and `/zarr/.zattrs` work fine.
*  fails with the same error.
* **Very interesting:** When I swapped the dataset with xarray.tutorial.open_dataset('air_temperature') I got the same error (but this time with the variable being "air" **only when using the OSN data!** When I intercepted w/ the requester pays S3 data I got a code=200 as expected.

## Call Stack
```  File "C:\Users\xrnogueira\Miniconda3\envs\catalog_to_xpublish_dev\Lib\site-packages\xpublish\plugins\included\zarr.py", line 41, in get_zarr_metadata
    zjson = jsonify_zmetadata(dataset, zmetadata)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xrnogueira\Miniconda3\envs\catalog_to_xpublish_dev\Lib\site-packages\xpublish\utils\zarr.py", line 142, in jsonify_zmetadata
    compressor = zjson['metadata'][f'{key}/{array_meta_key}']['compressor']
                 ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'air/.zarray'
```

# Background
## Version
```
{
  "python": "3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 17:59:51) [MSC v.1935 64 bit (AMD64)]",
  "python-bits": 64,
  "OS": "Windows",
  "OS-release": "10",
  "Version": "10.0.19043",
  "machine": "AMD64",
  "processor": "Intel64 Family 6 Model 140 Stepping 1, GenuineIntel",
  "byteorder": "little",
  "LC_ALL": "None",
  "LANG": "en_US.UTF-8",
  "LOCALE": "English_United States.1252",
  "libhdf5": "1.14.0",
  "libnetcdf": "4.9.2",
  "xarray": "2023.5.0",
  "zarr": "2.15.0",
  "numcodecs": "0.11.0",
  "fastapi": "0.97.0",
  "starlette": "0.27.0",
  "pandas": "2.0.2",
  "numpy": "1.25.0",
  "dask": "2023.6.0",
  "distributed": "2023.6.0",
  "uvicorn": "0.22.0"
}
```

## Datasets I tested with
### OSN Dataset (KeyError)
```
conus404-hourly-osn:
    driver: zarr
    description: "CONUS404 - OSN pod storage, 70 TB, 40 years of hourly data, CONUS extent with 4 km gridded spatial resolution, 157 variables"
    args:
      urlpath: 's3://rsignellbucket2/hytest/conus404/conus404_hourly_202302.zarr'
      consolidated: true
      storage_options:
        anon: true
        requester_pays: false
        client_kwargs:
          endpoint_url: https://renc.osn.xsede.org
```

### S3 Dataset (ValueError)
```
conus404-hourly-s3:
    driver: zarr
    description: "CONUS404 - s3 storage, 70 TB, 40 years of hourly data, CONUS extent with 4 km gridded spatial resolution, 157 variables"
    args:
      urlpath: 's3://nhgf-development/conus404/conus404_hourly_202209.zarr'
      consolidated: true
      storage_options:
        requester_pays: true
```
